//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        public LIBRO()
        {
            this.BIBLIOTECA = new HashSet<BIBLIOTECA>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string AUTOR { get; set; }
    
        public virtual ICollection<BIBLIOTECA> BIBLIOTECA { get; set; }
    }
}
